[preferred]
# Route screen capture and screenshot interfaces specifically to GNOME
org.freedesktop.impl.portal.ScreenCast=gnome
org.freedesktop.impl.portal.Screenshot=gnome

# Route file picking to Yazi
org.freedesktop.impl.portal.FileChooser=termfilechooser

# Use GTK or GNOME as fallback backends for all other standard interfaces
default=gtk;gnome;
