MBTN_LEFT cycle pause
MBTN_RIGHT script-binding positioning/drag-to-pan

UP add volume 5
DOWN add volume -5

# Make scroll wheel zoom in/out
WHEEL_UP script-binding positioning/cursor-centric-zoom 0.1
WHEEL_DOWN script-binding positioning/cursor-centric-zoom -0.1
