
# Make the temporary seek/volume bar smaller and lower
osd-bar=yes
osd-bar-w=80
osd-bar-h=2
osd-bar-align-y=0.96
osd-font-size=22
osd-level=1

keep-open=yes
volume=50

hr-seek=no

demuxer-hysteresis-secs=10

