listener {
    timeout = 300
    on-timeout = brightnessctl --class=backlight set 1% -s
    on-resume = brightnessctl --class=backlight -r
}

listener {
    timeout = 360
    on-timeout = hyprlock
}

listener {
    timeout = 370
    on-timeout = wlopm --off eDP-1
    on-resume = wlopm --on eDP-1
}

listener {
    timeout = 370
    on-timeout = wlopm --off DP-3
    on-resume = wlopm --on DP-3
}

listener {
    timeout = 1200
    on-timeout = systemctl suspend
}