general {
    no_fade_in = true
    no_fade_out = true
}

auth {
    fingerprint {
        enabled = true
        ready_message = Place finger to unlock
        present_message = Scanning...
        error_message = Not recognized
    }
}

background {
    color = rgb(1f1f1f)
}

input-field {
    size = 300, 50
    halign = center
    valign = center
}

label {
    text = $FPRINTPROMPT
    halign = center
    valign = center
    position = 0, -60
}
